### ISSUE TITLE
The program breakdown  when i use CUSLayout

### ISSUE THREAD

**Issue by DCRain** [JJMM/CUSLayout#3]
Hello, I have a try with your CUSLayout,but it always breakdown whit no reason ,there is no error information in XCode console panel. how should I do to deal whit it?

**Comment by JJMM** [comment]
Could you send crash stack and source code to me? Only use  the CUSLayout source code.

**Comment by JJMM** [comment]
@DCRain 
Thank you.I find and fix a bug in CUSGridLayout.
Please update CUSLayout and try again.
