### ISSUE TITLE
No such file or directory CUSLayout-Prefix.pch

### ISSUE THREAD

**Issue by zhangyongjiang** [JJMM/CUSLayout#4]
Thanks for the great work.

I'm trying to run the example but failed. The error is:

clang: error: no such file or directory: '..../CUSLayout/CUSLayout/CUSLayout-Prefix.pch'
clang: error: no input files

I have to copy the file to the CUSLayout/CUSLayout/ directory to fix the issue. 

By the way, could you please let me know how I can keep a view stick on the bottom of it's parent view? If it's not implemented yet, how I can modify the code to support it?

Thanks.

**Comment by JJMM** [comment]
1.There are nothing in "CUSLayout-Prefix.pch",so you can remove it.
You should follow the steps.
https://github.com/JJMM/CUSLayout/issues/1
Or use CocoaPods.
2. Please see the example of linnearLayout.Set the first view linnearData.fill to make it on the top.And the the second view will remain on the bottom.

**Comment by zhangyongjiang** [comment]
Sent you an email iosdes@163.com. Please check. Thanks.
